require("ufid.plugins-setup")
require("ufid.core.options")
require("ufid.core.keymaps")
require("ufid.core.colorscheme")
require("ufid.plugins.nvim-tree")
require("ufid.plugins.lualine")
require("ufid.plugins.nvim-cmp")
require("ufid.plugins.lsp.mason")
require("ufid.plugins.lsp.lspsaga")
require("ufid.plugins.lsp.lspconfig")

